### ISSUE TITLE
dont see the plugin anymore

### ISSUE THREAD

**Issue by darkwarden** [while-loop/runelite-plugins#10]
i cant find the zulrah plugin anymore in the sidebar.
reinstalled but didnt help.

**Comment by while-loop** [comment]
The panel now auto removes itself when not in Zulandra.

To disable that feature, uncheck the autohide box in the config menu. 


Also, hotkeys now only work when in the Zulrah instance.

**Comment by darkwarden** [comment]
got it ty.
