### ISSUE TITLE
"Investigate" is added twice in clan chat

### ISSUE THREAD

**Issue by SieBrum** [while-loop/runelite-plugins#16]
As title says. 

![image](https://user-images.githubusercontent.com/14212955/90191970-3cb35100-ddc2-11ea-8957-f2bdb29f95c5.png)

**Comment by while-loop** [comment]
@SieBrum do you happen to have the We Do Raids plugin installed?

**Comment by SieBrum** [comment]
![image](https://user-images.githubusercontent.com/14212955/90193718-d03a5100-ddc5-11ea-8f97-9d8d93b34889.png)
I do not

**Comment by while-loop** [comment]
Ah, i think i've found the issue. seems like it duplicates when you have the ability to kick others. I'll take a closer look into how to fix it.

**Comment by while-loop** [comment]
Thanks for the screenshot! That helped a bunch

**Comment by while-loop** [comment]
fixed in v2.0.2
