### ISSUE TITLE
Hard to see Jad phase icons

### ISSUE THREAD

**Issue by HughRaynor** [while-loop/runelite-plugins#3]
Great plugin, helped me get my first 10 Zulrah KC today. However, I keep having issues with the Jad phases. The split colouring of the circles is not clear enough to me, the pastel blue and green shades look quite similar. I've died a number of times as a result. Increasing the saturation of these colours should resolve this.

**Comment by while-loop** [comment]
Thanks for the feedback! 

I'll definitely work on this issue when I get some free time to work on runelite plugins.

I also have dark mode images in the works, so hopefully that could also help against color saturation (so be on the lookout for that too!).

I'll close this issue when your requests have been implemented.

**Comment by Vladutu** [comment]
Hi. I have the same issue with the colors. When do you think you will be able to increase the saturation of the colors?

**Comment by while-loop** [comment]
released in v1.0.1 :)
check the runelite-plugin in 1-2 days.

**Comment by Vladutu** [comment]
Nice! They are now clearly distinguishable. Also dark mode is a nice touch

**Comment by HughRaynor** [comment]
Awesome changes! I’ve learned the rotations now, but this will still help many others.

If you’re still looking for potential improvements, a small icon showing what to pray would be useful? Some range phases benefit from mage pray (for instance if it’s just spraying snakelings) and some phases benefit from changing half way.
