### ISSUE TITLE
RuneWatch - Please add optional cooldown for Alert On Nearby

### ISSUE THREAD

**Issue by puhtahtoe** [while-loop/runelite-plugins#33]
I like the feature but my chat log got filled up with alert messages. 

I was standing in a bank near a rooftop agility course so every time the person went around it added a message.

Alternatively, don't show the alert message if the person is on the player's ignore list.

**Comment by zahti** [comment]
Having the same issue while at Guardians of the Rift. I don't really want to see the message for the same person every time we enter/exit the altars and the main GOTR instance.

**Comment by Nick2bad4u** [comment]
Support! This happens so many times to me!!!

**Comment by Nick2bad4u** [comment]
Just to show you whats its like in GOTR:
![image](https://user-images.githubusercontent.com/20943337/220514918-a9613157-11d5-48ea-9f27-25663403b3b7.png)

**Comment by RuneWatch** [comment]
Potential timeout on recently 'seen' players would solve this issue, however this feature request would remove this problem completely: https://github.com/while-loop/runelite-plugins/issues/49

**Comment by Nick2bad4u** [comment]
> Potential timeout on recently 'seen' players would solve this issue, however this feature request would remove this problem completely: #49

That Feature request seems like a terrible and knee jerk reaction. It should in NO way be limited

**Comment by while-loop** [comment]
I'm also in favor of a cool down. Of course there are edge cases for location (and no need to keep an updated list for every new pvm area jagex releases).

**Comment by puhtahtoe** [comment]
Might I re-suggest the idea of not showing alerts for players you have ignored? I can't speak for everyone but I personally wouldn't have any desire to interact with someone who has made it to the RuneWatch list anyway. Also I can't see a reason why an ignored player would trigger an alert in the first place since if a player is on your ignore list it de facto means you don't need to be warned about them. 

I actually haven't played OSRS in several months now so maybe there's already been an update to this to not show alerts for ignored players in which case that's great but I'm pretty sure I tried ignoring someone back when I originally opened this topic. Regardless, it's good to see this getting some attention.

**Comment by while-loop** [comment]
to be released in v2.3.0 https://github.com/runelite/plugin-hub/pull/5024
