### ISSUE TITLE
Falsely accused from We Do Raids

### ISSUE THREAD

**Issue by 69Doug** [while-loop/runelite-plugins#37]
RuneWatch and We Do Raids does not have a case against me, but We Do Raids listed me as a "Scammer: Other"outside of PVM related content. I killed someone in (Player VS Player) wilderness area and now being accused of scamming for not splitting in PVM? Please fix this as it makes no sense.

**Comment by while-loop** [comment]
Hey! Please reach out to We Do raids and Runewatch. I don't control the lists.

**Comment by 69Doug** [comment]
I have and they are refusing to fix it. I don't know who else to contact.

**Comment by while-loop** [comment]
I don't control the list, so I can't help here. Sorry.

**Comment by 69Doug** [comment]
The purpose of your program is to do justice and protect people correct? Ignoring this post is the opposite.

**Comment by while-loop** [comment]
I'm not part of runewatch or wdr. I literally can't remove you even if I could. You're asking the wrong dude.

**Comment by 69Doug** [comment]
Ok so who is the owner of runewatch so I can contact them?

**Comment by while-loop** [comment]
@69Doug https://runewatch.com/faq
