### ISSUE TITLE
Zulrah Helper Hotkeys?

### ISSUE THREAD

**Issue by suuh-due** [while-loop/runelite-plugins#39]
@while-loop great work on the nice plugin for noobs like myself to help learn this boss haha. I do see it allows for hotkey settings, but no matter what keys I assign the hotkeys to none of them seem to work. Now I don't know if there is another plug-in or something missing that is not allowing me to run them. I've searched up, down, left, and right all over Youtube, google, Reddit, and GitHub to see if anyone else is having this problem. To conclude it appears not too many people really even use the hotkey function or those who do use it, have no problems with it. Was wondering if you could get back to me on a couple of things I could try to fix the issue I'm having. I would really love to be able to hotkey switch the phases, and stuff while keeping my mouse on the main game ready for anything that might happen. Thanks, and looking forward to your response!

**Comment by while-loop** [comment]
Hey hey 👋👋

Quick question, are you in the instance when trying the hotkeys? They're disabled when not in zulandra to allow people to enter their login and type as normal outside of Zulrah.

**Comment by suuh-due** [comment]
Hey, Yea before I was, but all I did now was uninstall the plug-in, Re-launch Runelite and installed it again, and now it works. Thanks again sorry if I bothered you, and nice work on the wonderful plug-in!! Have a nice day.

**Comment by while-loop** [comment]
No worries!! Glad you were able to make it work
