### ISSUE TITLE
Gauntlet Plugin does not track shards dropped from monsters

### ISSUE THREAD

**Issue by WiggleNibble** [while-loop/runelite-plugins#41]
It tracks shards from resources not from monster drops. I tried restarting and turning off all plugins and only turning on gauntlet. No dice
![image](https://user-images.githubusercontent.com/110086391/184523273-f85606ac-ce2a-4d07-a4a7-bfeb92ab40d1.png)

**Comment by Dharr223** [comment]
I am also having this issue, but for fish tracking as well. Shards and fish are the 2 resources that can either be harvested or dropped from an NPC. The tracker ignores NPC drops.

**Comment by while-loop** [comment]
I'll be disabling the Gauntlet plugin soon. 
You should download the other "The Gauntlet" instead. It's a much better plugin!
- https://github.com/runelite/plugin-hub/pull/4963
