### ISSUE TITLE
FEATURE REQUEST: Reset button below final phase

### ISSUE THREAD

**Issue by ElevenDucks** [while-loop/runelite-plugins#44]
I'm a noob who never quite finishes the kill in one cycle, could you had the reset button at the bottom after the final phase to clearly indicate that its about to reset? Just thought it might make it a bit easier.

Could maybe even include that on reset you need to pray range first, unlike very first phase.

**Comment by raiyni** [comment]
Added in 4874ce2d27f39f0e134212a6b717e234cb9b27d3
