### ISSUE TITLE
[Feature Request] Limit Announcements

### ISSUE THREAD

**Issue by RuneWatch** [while-loop/runelite-plugins#49]
Hey,

After recent event's its bought forward some information, things we've not been told before, with regards to harassment so this is a request to limit announcements of players on the watchlist/s to the following:

1. PVM Areas
2. Joining chat channel
3. Trading

I'm not sure how easy it would be to achieve point 1, above, what are your thoughts?

Happy to discuss!, Thanks!

**Comment by Nick2bad4u** [comment]
I 100% disagree with this.

Scamming is an indicator of characteristics of a person's moral compass.

These things extend beyond just PvM. Limiting it to specific areas seems like a knee jerk reaction without much thought.

**Comment by Nick2bad4u** [comment]
I 100% disagree with this.

Scamming is an indicator of characteristics of a person's moral compass.

These things extend beyond just PvM. Limiting it to specific areas seems like a knee jerk reaction without much thought.

I can also see ways around this. Someone on the Runewatch list tries to borrow gear again from someone - the "someone" lets them borrow gear and the person jump's on an alt to accept.

I believe we should do the opposite of this and instead, make sure that a RuneWatch icon shows on friends lists.
