### ISSUE TITLE
[Gauntlet][Bug] Resource tracker does not count shards obtained from breaking down demi-boss drops

### ISSUE THREAD

**Issue by ArnavSubramanya** [while-loop/runelite-plugins#53]
Corrupted orbs, bowstrings, and spikes can be broken down into 80 crystal shards by using them on a pestle and mortar. When you do this, your shard counter does not update to reflect the additional shards you've gotten

**Comment by while-loop** [comment]
I'll be disabling the Gauntlet plugin soon. 
You should download the other "The Gauntlet" instead. It's a much better plugin!
- https://github.com/runelite/plugin-hub/pull/4963
