### ISSUE TITLE
Bug: usernames are spammed every 7-8 seconds over and over again

### ISSUE THREAD

**Issue by Sponsorn** [while-loop/runelite-plugins#54]
While mining crashed stars I found a bug where a username was spammed every 7 seconds, same message every time 

![image](https://github.com/while-loop/runelite-plugins/assets/59361120/141359cf-c92d-4722-8e29-4916b2f8ef1f)

Expected behaviour: check if username is posted within a time window of x minutes/hours, if no: send message; if yes: dont send 🙃

Bug was encountered with a lot of players nearby (>200)

**Comment by while-loop** [comment]
to be released in v2.3.0 https://github.com/runelite/plugin-hub/pull/5024
