### ISSUE TITLE
runewatch

### ISSUE THREAD

**Issue by pettrs** [while-loop/runelite-plugins#56]
can there be added an option to disable/hide rightclick investigate. i'm trying to cut down on plugins that overflood my client, but I don't want to disable runewatch all together.

![image](https://github.com/while-loop/runelite-plugins/assets/75093127/b1d4d749-f007-4097-8715-267201025e12)

**Comment by while-loop** [comment]
The plug-in has a config to remove the investigate from the player right click menu
