### ISSUE TITLE
Zulrah helper resetting itself mid fight

### ISSUE THREAD

**Issue by kiukkukisu** [while-loop/runelite-plugins#6]
I have not been able to figure out what triggers this, it seems randomly mid fight the plugin just resets itself. I have bound only next phase to a button, the reset binding says "Not set" and I have also tried to reset the plugin configuration if there was some ghost key bound to reset but no luck there, still resetting randomly. Some times it just resets when I'm moving to next position not pressing any keys. This started to happen after v1.2.0 so could have something to do with the "Hide when outside of Zul-Andra" setting. I really hope I could give you more detailed explanation :(
EDIT: It still happens if you disable the "Hide when outside of Zul-Andra" setting.

**Comment by ImLoader** [comment]
Yea Im having the same issue, seems like the "reset" button is highlighted when you reset it once, and mine resets when i hit space bar. None of the phase keys work either

**Comment by kiukkukisu** [comment]
Okay I think I figured it out, it resets itself all the time if you standing at south side of the Zulrah island. All area south of the southern pillars resets it all the time.

**Comment by kiukkukisu** [comment]
> Yea Im having the same issue, seems like the "reset" button is highlighted when you reset it once, and mine resets when i hit space bar. None of the phase keys work either

None of the hotkeys work for me either if I'm outside of Zul-Andra. I guess the resetting by pressing Spacebar is because the Reset button is highlighted and you "press" it when you press Spacebar

**Comment by gustavo0818** [comment]
After today's update the error plug ...
Whenever I select the rotation the plug restarts and returns to rotation 0

**Comment by while-loop** [comment]
Thanks for the issue report all! 

The recent update reset the rotations when entering Zulrah, but it seems that it's triggering it more than once in the instance. I will revert that change.

> None of the hotkeys work for me either if I'm outside of Zul-Andra but maybe that is the point

Yes that is the point. Some of the runelite maintainers and other users suggested that hotkeys are only enabled within the Zulrah instance. Many users map keys 1,2,3 to selections so entering passwords and typing in chat wasn't possible.

**Comment by while-loop** [comment]
v1.2.1 has been released to the plugin hub. The panel will no longer auto reset itself.

**Comment by gustavo0818** [comment]
Very thanks for you

**Comment by kiukkukisu** [comment]
Thank you! Good job with the plugin, it's really convenient way to learn the rotations.
