### ISSUE TITLE
Zulrah Helper

### ISSUE THREAD

**Issue by Bailey-Alger** [while-loop/runelite-plugins#61]
Phase MAGMA_A #4 is incorrect. During that phase Zulrah venom clouds the area it says to stand in. You're suppose to move to the right side _before_ phase #9.

**Comment by raiyni** [comment]
Sorry, I meant to update this when I got added but leagues came out and I didn't get back on zulrah right away.

**Comment by raiyni** [comment]
@Bailey-Alger MAGMA_A 4 seems correct? 
![image](https://github.com/while-loop/runelite-plugins/assets/22979513/ef7a97a6-fa2a-4653-9338-8be562068051)

**Comment by raiyni** [comment]
I did fix a few locations that seemed wrong/sub optimal.
