### ISSUE TITLE
Zulrah Location incorrect

### ISSUE THREAD

**Issue by Shmeaters** [while-loop/runelite-plugins#64]
When zulrah goes from start green phase to green phase, the location should be bottom right as he throws out venom clouds. I believe the location is set to top left. See screenshot

**Comment by Shmeaters** [comment]
![Screenshot 2024-05-15 134555](https://github.com/while-loop/runelite-plugins/assets/169934050/c44804ca-335c-4b9a-95c9-1af44f3d76ce)

**Comment by raiyni** [comment]
I don't know what you are referencing but that location is right.

**Comment by Shmeaters** [comment]
My apologies, I have rewatched a couple guides thinking I was going insane. Appreciate the response.
