### ISSUE TITLE
Zulrah Helper plugin is showing wrong phase info

### ISSUE THREAD

**Issue by chrisdola** [while-loop/runelite-plugins#66]
I am not sure when this issue began as it's been a minute since I've used the Zulrah Helper plugin. However, I noticed today that several of the icons for some of the phases are just wrong. When I tested it today, I had the range phase as #2. The plugin says that next after that is melee where you stand on the left pillar. That is incorrect... The correct and only spot to stand is marked in the screenshot attached. 

I think this is worth testing more because I noticed some chatter in the discord as well about how some of the other phases are showing incorrect images as well. 

On top of that, the JAD phase icons are noticeably removed. I'm not sure if this change was intentional or if it is also a result of the images for the phases being shifted out of order somehow. 

![image](https://github.com/while-loop/runelite-plugins/assets/124531934/06707cf0-cb2f-495c-af1b-89044566c118)

**Comment by raiyni** [comment]
This spot is correct. You can show jad phases with prayers enabled.

**Comment by cpbr-dev** [comment]
> This spot is correct. You can show jad phases with prayers enabled.

Why the sudden change ? The old icon was understandable without adding prayers to clutter the image.
More information on screen is not always better.
