### ISSUE TITLE
[Bug] (zulrah-helper) Attack style icon no longer displays the Jad phase attack order

### ISSUE THREAD

**Issue by AustinMcPhail** [while-loop/runelite-plugins#67]
Small attack style icon no longer shows both attack styles.
Seems to be related to [this commit](https://github.com/while-loop/runelite-plugins/commit/25faefc342d1fd5a6691e04f18646e6bf62d7056).

![image](https://github.com/while-loop/runelite-plugins/assets/5369192/fac97b2f-a188-4f01-979b-19226923a1cc)

![image](https://github.com/while-loop/runelite-plugins/assets/5369192/8e265d90-d27a-47d6-b06a-ff7bcbcfb632)

**Comment by raiyni** [comment]
The prayer icons show it.
