### ISSUE TITLE
Issue with Zulrah Helper not showing when Jad Phase occurs with the split 'Range / Mage' circle 

### ISSUE THREAD

**Issue by CLennonM1990** [while-loop/runelite-plugins#69]
<img width="168" alt="image" src="https://github.com/user-attachments/assets/734438a0-51b2-4739-85f2-3bbc2f7d260b">
<img width="173" alt="image" src="https://github.com/user-attachments/assets/be948c3c-6a37-43ca-84df-c3951c4ba2bc">
<img width="177" alt="image" src="https://github.com/user-attachments/assets/a8817b2e-b31c-4950-8687-39ce62e629ca">

As per title really. Not sure how long this has been happening as not been to Zulrah for a while but the helper used to show when the Jad phase was going happen and which order the attacks would occur. Now there is no indication at all.

**Comment by raiyni** [comment]
You can  enable prayer icons https://github.com/while-loop/runelite-plugins/issues/67

**Comment by Mordo95** [comment]
Literally a UX change that didn't need updating, when learning now I first have to explicity enable prayer icons and it throws me off every time due to how small the icons are on a high resolution screen.

**Comment by CLennonM1990** [comment]
> Literally a UX change that didn't need updating, when learning now I first have to explicity enable prayer icons and it throws me off every time due to how small the icons are on a high resolution screen.

Yea. New one is terrible. Old one was so much better
