### ISSUE TITLE
Zulrah Helper does not allow me to use Hotkeys set.

### ISSUE THREAD

**Issue by KillingMenz** [while-loop/runelite-plugins#9]
Hello, 

I've been trying to setup the plugin to my settings. I have it setup as Phase 1 F1 - Phase 2 - F2       Phase 3 - F3 with next phase set to F4, nothing overlapping but none of them would change the phases. I then switched keys to 1,2,3,4 Respectively and the same issue. I did not have any other plugins that could interfere (key remapping, etc.) to my knowledge. Had some assistance in runelite discord but we could not figure it out. 

Thanks.

**Comment by while-loop** [comment]
Hiya! HotKeys will only work once inside the Zulrah instance.

This was a change because most people will remap single letters (and in your case F1 keys) and will override it when doing normal in-game things.

**Comment by KillingMenz** [comment]
Ahh ok, apologies thought it was a bug on my end or something. Thanks for the help, great plugin. Cheers!
